# $ docker run --name  -e  -e  -e  -p 5432:5432 bitnami/postgresql
#yaml Ã© identado como o python
version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid